### ISSUE TITLE
2.4.0 Release Plan

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/lit-element#1051]
# 2.4.0 Release Plan

Release Plan that outlines the focused tasks for lit-element 2.4.0.

[Milestone](https://github.com/Polymer/lit-html/milestone/14)

## Notable Changes
- Enhancements
  - [x] [Add query decorator options](https://github.com/Polymer/lit-element/pull/1032)
  - [x] [As a developer I would like to do sync actions on property changes](https://github.com/Polymer/lit-element/issues/643)
- Bug Fixes
  - [x] [queryAssignedNodes doesn't correctly locate default slot](https://github.com/Polymer/lit-element/issues/1002)

## Documentation

Lots of committed document changes, already deployed. No pending documentation changes.

## Release Process
- [x] [Run Google Internal Tests](https://github.com/Polymer/lit-element/issues/1048)
- [ ] [2.4.0 Release Notes](https://github.com/Polymer/lit-element/issues/1049)
- [ ] [Verify 2.4.0 CHANGELOG](https://github.com/Polymer/lit-element/issues/1050)

**Comment by Westbrook** [comment]
Excited for this, as I've just refactored something to use `queryAssignedNodes` only to find the issue that'll be fixed in this release. Is there a rough timeline that you could share?
